name: Basic CI Workflow

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  run-calculator:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run calculator app
        run: 
          export CI=true python src/main.py
